export const cards = [
  {
    title: "Premium car rental",
    description: "Ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "./assets/card1.jpg",
    link: "#",
  },
  {
    title: "Sport car rental",
    description: "lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "./assets/card2.jpg",
    link: "#",
  },
  {
    title: "Limousine rental",
    description: "lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "./assets/card3.jpg",
    link: "#",
  },
  {
    title: "Safety & insurance",
    description: "lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "./assets/card4.jpg",
    link: "#",
  },
  {
    title: "How to book a car",
    description: "lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "./assets/card5.jpg",
    link: "#",
  },
];

export const states = [
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const services = [
  {
    title: "All inclusive pricing",
    description: "lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "./assets/gal1.png",
  },
  {
    title: "No hidden charges",
    description: "lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "./assets/gal1.png",
  },
  {
    title: "Leading suppliers worldwide",
    description: "lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "./assets/gal1.png",
  },
  {
    title: "Lowest price guarantee",
    description: "lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "./assets/gal1.png",
  },
];
